name: PET STORE SMOKE TESTS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/emailable-report.html

      - name: Send test report email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ job.status }} - API TEST
          body: Test results attached.
          to: kg@daxap.io
          from: Pet Store Api Test
          attachments: target/surefire-reports/emailable-report.html